---
new_page_extension: md
auto_deploy: false
admin_path: admin
webhook_url: 
sections:
- type: directory
  path: src/contents
  label: Blog Posts
  create: all
  match: "**/*"
upload_dir: ''
public_path: https://res.cloudinary.com/dcu0dsel9/image/upload/c_scale,w_auto:100,dpr_auto
front_matter_path: https://res.cloudinary.com/dcu0dsel9/image/upload
use_front_matter_path: true
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
